dist: trusty
sudo: false

language: python

python:
 - "3.4"
 - "3.5"
 - "3.6"
  
services:

env:
  -DJANGO_VERSION=1.11

install:
 - pip install .

script:
 - python manage.py test

 notifications:
    email: false
 
