dist: trusty
sudo: false

language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
  
env:
  - DJANGO_PKG="Django==1.11"

# /home/travis/build/scaramallion/django-rt-pdb is wd
install:
 - pip install $DJANGO_PKG
 - pip install ./

script:
 - django-admin.py test --settings=pdbook.tests.test_settings pdbook
notifications:
    email: false
 
