dist: trusty
sudo: false

language: python

python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
  
env:
  - DJANGO_PKG="Django==1.11"

install:
 - pip install $DJANGO_PKG
 - pip install .

script:
 - PYTHONPATH=. DJANGO_SETTINGS_MODULE=pdbook.tests.test_settings django-admin test

notifications:
    email: false
 
